# Generated by Django 2.2.7 on 2019-11-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=45)),
                ('dia_semana', models.CharField(max_length=45)),
            ],
        ),
    ]
